# Cortex SAST Rules Engine
# All rules map to OWASP Mobile Top 10 2024 + MASVS v2.0

OWASP_MOBILE = {
    "M1":  "Improper Credential Usage",
    "M2":  "Inadequate Supply Chain Security",
    "M3":  "Insecure Authentication/Authorization",
    "M4":  "Insufficient Input/Output Validation",
    "M5":  "Insecure Communication",
    "M6":  "Inadequate Privacy Controls",
    "M7":  "Insufficient Binary Protections",
    "M8":  "Security Misconfiguration",
    "M9":  "Insecure Data Storage",
    "M10": "Insufficient Cryptography",
}

MASVS = {
    "MASVS-STORAGE-1":    "Data is stored securely on the device",
    "MASVS-STORAGE-2":    "Sensitive data is not shared with third parties unnecessarily",
    "MASVS-CRYPTO-1":     "Strong, industry-standard cryptographic primitives are used",
    "MASVS-CRYPTO-2":     "Cryptographic keys are managed securely",
    "MASVS-AUTH-1":       "Authentication is implemented securely",
    "MASVS-AUTH-2":       "Session management is implemented securely",
    "MASVS-NETWORK-1":    "Data is encrypted in transit",
    "MASVS-NETWORK-2":    "TLS settings are in line with best practices",
    "MASVS-PLATFORM-1":   "The app uses IPC mechanisms securely",
    "MASVS-PLATFORM-2":   "The app uses WebViews securely",
    "MASVS-PLATFORM-3":   "The app uses third-party components securely",
    "MASVS-CODE-1":       "The app requires an up-to-date platform version",
    "MASVS-CODE-2":       "The app only uses necessary permissions",
    "MASVS-CODE-3":       "Security-relevant functionality is not exposed unnecessarily",
    "MASVS-CODE-4":       "The app has basic code quality protections",
    "MASVS-RESILIENCE-1": "The app validates the integrity of the platform",
    "MASVS-RESILIENCE-2": "The app implements anti-tampering mechanisms",
    "MASVS-RESILIENCE-3": "The app implements anti-static analysis mechanisms",
    "MASVS-RESILIENCE-4": "The app implements anti-dynamic analysis techniques",
}

# ─── SAST CODE RULES ─────────────────────────────────────────────────────────
# Each rule: id, title, pattern (regex on smali/dex strings), severity,
# category, cwe, masvs, owasp, description, recommendation, poc (optional)
CODE_RULES = [

    # ── WebView ───────────────────────────────────────────────────────────────
    {
        "id":          "android_webview_ignore_ssl",
        "title":       "WebView SSL Certificate Errors Ignored",
        "pattern":     r"onReceivedSslError.{0,200}proceed\(\)",
        "severity":    "critical",
        "category":    "WebView",
        "cwe":         "CWE-295",
        "masvs":       "MASVS-NETWORK-2",
        "owasp":       "M5",
        "description": "WebView overrides onReceivedSslError and calls handler.proceed(), silently ignoring all SSL certificate errors including invalid, expired, and MitM certificates.",
        "impact":      "App is fully vulnerable to MitM attacks. Any attacker on the same network can intercept all WebView HTTPS traffic.",
        "recommendation": "Remove handler.proceed() from onReceivedSslError. Display an error to the user and cancel the load.",
    },
    {
        "id":          "android_webview_js_enabled",
        "title":       "WebView JavaScript Enabled",
        "pattern":     r"setJavaScriptEnabled\(true\)",
        "severity":    "medium",
        "category":    "WebView",
        "cwe":         "CWE-749",
        "masvs":       "MASVS-PLATFORM-2",
        "owasp":       "M4",
        "description": "WebView has JavaScript execution enabled. Combined with other WebView misconfigurations, this can enable XSS, file access, and remote code execution.",
        "recommendation": "Only enable JavaScript if required for functionality. Validate all content loaded in WebView. Never load attacker-controlled URLs.",
    },
    {
        "id":          "android_webview_javascript_interface",
        "title":       "WebView addJavascriptInterface — RCE Surface",
        "pattern":     r"addJavascriptInterface\(",
        "severity":    "high",
        "category":    "WebView",
        "cwe":         "CWE-749",
        "masvs":       "MASVS-PLATFORM-2",
        "owasp":       "M4",
        "description": "addJavascriptInterface() exposes a Java object to JavaScript. On Android < 4.2 this allows arbitrary code execution via reflection. On newer versions, only @JavascriptInterface-annotated methods are exposed, but XSS can still call them.",
        "recommendation": "Avoid addJavascriptInterface if possible. If required, use @JavascriptInterface annotations, validate all JS input, and ensure only trusted content is loaded.",
    },
    {
        "id":          "android_webview_file_access",
        "title":       "WebView File System Access Enabled",
        "pattern":     r"setAllowFileAccess\(true\)|setAllowFileAccessFromFileURLs\(true\)|setAllowUniversalAccessFromFileURLs\(true\)",
        "severity":    "high",
        "category":    "WebView",
        "cwe":         "CWE-200",
        "masvs":       "MASVS-PLATFORM-2",
        "owasp":       "M1",
        "description": "WebView file access is enabled. Combined with setJavaScriptEnabled, this can allow JavaScript to read any file accessible to the app, including shared preferences, databases, and tokens.",
        "recommendation": "Set setAllowFileAccess(false), setAllowFileAccessFromFileURLs(false), setAllowUniversalAccessFromFileURLs(false) unless explicitly required.",
    },
    {
        "id":          "android_webview_geolocation",
        "title":       "WebView Geolocation Access Enabled",
        "pattern":     r"setGeolocationEnabled\(true\)",
        "severity":    "medium",
        "category":    "WebView",
        "cwe":         "CWE-359",
        "masvs":       "MASVS-PLATFORM-2",
        "owasp":       "M6",
        "description": "WebView geolocation API is enabled. Loaded web content can access the user's precise location.",
        "recommendation": "Disable geolocation unless required. Implement proper user consent flow.",
    },
    {
        "id":          "android_webview_mixed_content",
        "title":       "WebView Mixed Content Allowed",
        "pattern":     r"setMixedContentMode\s*\(\s*[^)]*MIXED_CONTENT_ALWAYS_ALLOW",
        "severity":    "high",
        "category":    "WebView",
        "cwe":         "CWE-319",
        "masvs":       "MASVS-NETWORK-1",
        "owasp":       "M3",
        "description": "WebView is set to MIXED_CONTENT_ALWAYS_ALLOW, letting an HTTPS page load HTTP sub-resources (scripts, iframes, XHR). An on-path attacker can inject content into the otherwise-secure page.",
        "recommendation": "Use MIXED_CONTENT_NEVER_ALLOW (the default on modern Android). Serve all WebView resources over HTTPS.",
    },
    {
        "id":          "android_webview_local_storage",
        "title":       "WebView DOM Storage / Local Storage Enabled",
        "pattern":     r"setDomStorageEnabled\(true\)",
        "severity":    "low",
        "category":    "WebView",
        "cwe":         "CWE-312",
        "masvs":       "MASVS-STORAGE-1",
        "owasp":       "M9",
        "description": "WebView DOM storage is enabled. Loaded pages can store data in localStorage, which persists on the device.",
        "recommendation": "Only enable if required. Ensure sensitive data is not stored in localStorage.",
    },

    # ── Cryptography ──────────────────────────────────────────────────────────
    {
        "id":          "android_weak_hash_md5",
        "title":       "Weak Hash Algorithm — MD5",
        "pattern":     r'MessageDigest\.getInstance\("MD5"\)|MessageDigest\.getInstance\("md5"\)',
        "severity":    "high",
        "category":    "Cryptography",
        "cwe":         "CWE-327",
        "masvs":       "MASVS-CRYPTO-1",
        "owasp":       "M10",
        "description": "MD5 is a cryptographically broken hash function. Collisions can be generated in milliseconds. If used for password hashing or data integrity, it provides no security.",
        "recommendation": "Replace MD5 with SHA-256 or SHA-3 for integrity checks. For passwords, use bcrypt, scrypt, or Argon2.",
    },
    {
        "id":          "android_weak_hash_sha1",
        "title":       "Weak Hash Algorithm — SHA-1",
        "pattern":     r'MessageDigest\.getInstance\("SHA-1"\)|MessageDigest\.getInstance\("SHA1"\)',
        "severity":    "medium",
        "category":    "Cryptography",
        "cwe":         "CWE-327",
        "masvs":       "MASVS-CRYPTO-1",
        "owasp":       "M10",
        "description": "SHA-1 is deprecated for security use. Practical collision attacks exist. Google deprecated SHA-1 certificates in Chrome in 2017.",
        "recommendation": "Migrate to SHA-256 or SHA-3.",
    },
    {
        "id":          "android_weak_cipher_des",
        "title":       "Weak Cipher — DES / 3DES",
        "pattern":     r'Cipher\.getInstance\("DES[^"]{0,20}"\)|Cipher\.getInstance\("TripleDES[^"]{0,20}"\)',
        "severity":    "high",
        "category":    "Cryptography",
        "cwe":         "CWE-327",
        "masvs":       "MASVS-CRYPTO-1",
        "owasp":       "M10",
        "description": "DES has a 56-bit key space and can be brute-forced in hours. 3DES is deprecated as of 2023 (NIST SP 800-131A). Both are considered insecure.",
        "recommendation": "Replace with AES-256-GCM.",
    },
    {
        "id":          "android_weak_cipher_ecb",
        "title":       "Weak Cipher Mode — ECB",
        "pattern":     r'Cipher\.getInstance\("[^"]+/ECB/[^"]*"\)',
        "severity":    "high",
        "category":    "Cryptography",
        "cwe":         "CWE-327",
        "masvs":       "MASVS-CRYPTO-1",
        "owasp":       "M10",
        "description": "ECB (Electronic Codebook) mode is deterministic — identical plaintext blocks produce identical ciphertext. This leaks data patterns and is fundamentally insecure for encrypting real data.",
        "recommendation": "Use AES/GCM/NoPadding (authenticated encryption) or AES/CBC/PKCS5Padding with a random IV.",
    },
    {
        "id":          "android_cbc_padding_oracle",
        "title":       "CBC Mode with PKCS Padding — Padding Oracle Risk",
        "pattern":     r'Cipher\.getInstance\("[^"]+/CBC/PKCS[57]Padding"\)',
        "severity":    "medium",
        "category":    "Cryptography",
        "cwe":         "CWE-326",
        "masvs":       "MASVS-CRYPTO-1",
        "owasp":       "M10",
        "description": "CBC mode with PKCS5/PKCS7 padding is vulnerable to padding oracle attacks if error responses are distinguishable. This allows decryption of ciphertext without the key.",
        "recommendation": "Prefer AES/GCM/NoPadding which provides authenticated encryption and is not vulnerable to padding oracle attacks.",
    },
    {
        "id":          "android_insecure_random",
        "title":       "Insecure Random Number Generator",
        "pattern":     r"new Random\(\)|Math\.random\(\)|java\.util\.Random",
        "severity":    "medium",
        "category":    "Cryptography",
        "cwe":         "CWE-330",
        "masvs":       "MASVS-CRYPTO-1",
        "owasp":       "M10",
        "description": "java.util.Random is a pseudorandom number generator (PRNG) not suitable for security-sensitive contexts like key generation, tokens, nonces, or session IDs.",
        "recommendation": "Use java.security.SecureRandom for any security-sensitive random number generation.",
    },
    {
        "id":          "android_weak_iv",
        "title":       "Hardcoded or Predictable IV",
        "pattern":     r"IvParameterSpec\(new byte\[",
        "severity":    "high",
        "category":    "Cryptography",
        "cwe":         "CWE-329",
        "masvs":       "MASVS-CRYPTO-2",
        "owasp":       "M10",
        "description": "Initialization Vector (IV) may be hardcoded or zero-initialized. A static IV defeats the purpose of CBC/CTR mode encryption.",
        "recommendation": "Always generate IVs using SecureRandom. Store the IV alongside the ciphertext.",
    },
    {
        "id":          "android_weak_cipher_rc4",
        "title":       "Weak Cipher — RC4",
        "pattern":     r'(?:Cipher|KeyGenerator)\.getInstance\("(?:RC4|ARCFOUR)[^"]*"\)',
        "severity":    "high",
        "category":    "Cryptography",
        "cwe":         "CWE-327",
        "masvs":       "MASVS-CRYPTO-1",
        "owasp":       "M10",
        "description": "RC4 is a broken stream cipher with well-known biases and practical attacks. It must not be used to protect data.",
        "recommendation": "Replace RC4 with AES-GCM (authenticated encryption).",
    },
    {
        "id":          "android_aes_ecb_default",
        "title":       "AES Default Mode (ECB)",
        # Cipher.getInstance("AES") with no mode defaults to ECB on Android.
        "pattern":     r'Cipher\.getInstance\("AES"\)',
        "severity":    "high",
        "category":    "Cryptography",
        "cwe":         "CWE-327",
        "masvs":       "MASVS-CRYPTO-1",
        "owasp":       "M10",
        "description": "Cipher.getInstance(\"AES\") with no mode defaults to ECB, which is deterministic and leaks plaintext structure.",
        "recommendation": "Specify an authenticated mode explicitly, e.g. AES/GCM/NoPadding with a random IV.",
    },
    {
        "id":          "android_static_salt",
        "title":       "Hardcoded Salt",
        "pattern":     r'PBEKeySpec\([^,]+,\s*(?:"[^"]+"|new byte\[\]\s*\{)|byte\[\]\s+salt\s*=\s*(?:"|\{|new byte\[\]\s*\{)',
        "severity":    "medium",
        "category":    "Cryptography",
        "cwe":         "CWE-760",
        "masvs":       "MASVS-CRYPTO-2",
        "owasp":       "M10",
        "description": "A hardcoded/static salt makes password hashes precomputable (rainbow tables) and defeats per-credential uniqueness.",
        "recommendation": "Generate a random salt per credential with SecureRandom and store it alongside the hash.",
    },
    {
        "id":          "android_weak_pbkdf_iterations",
        "title":       "Weak PBKDF Iteration Count",
        # PBEKeySpec(password, salt, iterations, keyLen) with a 1-4 digit iteration
        # count (< 10000, below OWASP guidance).
        "pattern":     r'PBEKeySpec\([^,]+,[^,]+,\s*[0-9]{1,4}\s*,',
        "severity":    "medium",
        "category":    "Cryptography",
        "cwe":         "CWE-916",
        "masvs":       "MASVS-CRYPTO-1",
        "owasp":       "M10",
        "description": "PBKDF2 iteration count is below recommended guidance (OWASP: ≥ 600k for PBKDF2-HMAC-SHA256), making offline brute-force cheaper.",
        "recommendation": "Raise the iteration count to current OWASP guidance, or use Argon2/scrypt.",
    },
    {
        "id":          "android_weak_rsa_keygen",
        "title":       "Weak RSA Key Size (keygen)",
        "pattern":     r'\.initialize\(\s*(?:512|1024)\s*[,)]',
        "severity":    "high",
        "category":    "Cryptography",
        "cwe":         "CWE-326",
        "masvs":       "MASVS-CRYPTO-1",
        "owasp":       "M10",
        "description": "RSA/DSA key generated with a ≤1024-bit modulus is considered weak and factorable by well-resourced attackers.",
        "recommendation": "Use ≥ 2048-bit RSA (3072+ preferred) or an EC key (P-256+).",
    },
    {
        "id":          "android_java_hashcode",
        "title":       "Java .hashCode() Used as Hash Function",
        "pattern":     r"\.hashCode\(\)",
        "severity":    "medium",
        "category":    "Cryptography",
        "cwe":         "CWE-328",
        "masvs":       "MASVS-CRYPTO-1",
        "owasp":       "M10",
        "description": "Java's .hashCode() is not a cryptographic hash function. It is not collision-resistant and must never be used for security purposes.",
        "recommendation": "Use MessageDigest with SHA-256 for cryptographic hash requirements.",
    },
    {
        "id":          "android_base64_encoding",
        "title":       "Base64 Encoding Used as Encryption",
        "pattern":     r"Base64\.encode|Base64\.encodeToString",
        "severity":    "low",
        "category":    "Cryptography",
        "cwe":         "CWE-311",
        "masvs":       "MASVS-CRYPTO-1",
        "owasp":       "M10",
        "description": "Base64 encoding detected. Base64 is encoding, not encryption. If used to 'protect' sensitive data, it provides zero security — it is trivially reversible.",
        "recommendation": "Use actual encryption (AES-GCM) for sensitive data. Do not mistake encoding for encryption.",
    },

    # ── Data Storage ──────────────────────────────────────────────────────────
    {
        "id":          "android_world_readable_file",
        "title":       "World-Readable File Created",
        "pattern":     r"MODE_WORLD_READABLE|openFileOutput\([^,]+,\s*1\b",
        "severity":    "high",
        "category":    "Data Storage",
        "cwe":         "CWE-312",
        "masvs":       "MASVS-STORAGE-1",
        "owasp":       "M9",
        "description": "App creates files with MODE_WORLD_READABLE, making them accessible to all other apps on the device.",
        "recommendation": "Use MODE_PRIVATE (default) for all file operations. Never use world-readable or world-writable modes.",
    },
    {
        "id":          "android_world_writable_file",
        "title":       "World-Writable File Created",
        "pattern":     r"MODE_WORLD_WRITEABLE|openFileOutput\([^,]+,\s*2\b",
        "severity":    "high",
        "category":    "Data Storage",
        "cwe":         "CWE-312",
        "masvs":       "MASVS-STORAGE-1",
        "owasp":       "M9",
        "description": "App creates files with MODE_WORLD_WRITEABLE, allowing any app to modify them. This can lead to data tampering or privilege escalation.",
        "recommendation": "Use MODE_PRIVATE for all file operations.",
    },
    {
        "id":          "android_external_storage_write",
        "title":       "Writing to External Storage",
        "pattern":     r"getExternalStorageDirectory|getExternalFilesDir|getExternalCacheDir|Environment\.getExternalStorage",
        "severity":    "medium",
        "category":    "Data Storage",
        "cwe":         "CWE-312",
        "masvs":       "MASVS-STORAGE-1",
        "owasp":       "M9",
        "description": "App writes data to external storage (SD card). Any app with READ_EXTERNAL_STORAGE permission can read this data. External storage is not suitable for sensitive information.",
        "recommendation": "Store sensitive data in internal storage only. If external storage is needed, encrypt data before writing.",
    },
    {
        "id":          "android_shared_prefs_mode_world",
        "title":       "SharedPreferences World-Accessible Mode",
        "pattern":     r"getSharedPreferences\([^,]+,\s*(?:1|2|MODE_WORLD_READABLE|MODE_WORLD_WRITEABLE)",
        "severity":    "high",
        "category":    "Data Storage",
        "cwe":         "CWE-312",
        "masvs":       "MASVS-STORAGE-1",
        "owasp":       "M9",
        "description": "SharedPreferences created with world-readable or world-writable mode. Any app can access this data.",
        "recommendation": "Always use MODE_PRIVATE for SharedPreferences.",
    },
    {
        "id":          "android_sqlite_raw_query",
        "title":       "Raw SQL Query — SQL Injection Risk",
        "pattern":     r"rawQuery\(|execSQL\(|compileStatement\(",
        "severity":    "high",
        "category":    "Data Storage",
        "cwe":         "CWE-89",
        "masvs":       "MASVS-CODE-4",
        "owasp":       "M4",
        "description": "App uses raw SQL queries. If user-controlled data is concatenated into SQL strings, SQL injection is possible in the local SQLite database.",
        "recommendation": "Use parameterized queries (db.query() with selectionArgs) or Room ORM. Never concatenate user input into SQL strings.",
    },
    {
        "id":          "android_encryption_key_hardcoded",
        "title":       "Hardcoded Encryption Key",
        "pattern":     r'SecretKeySpec\(.*"[A-Za-z0-9+/=]{8,}".getBytes|SecretKeySpec\(.*\.getBytes\("',
        "severity":    "critical",
        "category":    "Cryptography",
        "cwe":         "CWE-321",
        "masvs":       "MASVS-CRYPTO-2",
        "owasp":       "M10",
        "description": "Encryption key may be hardcoded as a string literal. Any analyst can extract this key by decompiling the app, rendering all encryption useless.",
        "recommendation": "Generate keys using KeyGenerator and store in Android Keystore system. Never hardcode cryptographic keys.",
    },

    # ── Logging ───────────────────────────────────────────────────────────────
    {
        "id":          "android_log_debug",
        "title":       "Sensitive Data May Be Logged (Log.d/v/i)",
        "pattern":     r"\bLog\.(d|v|i|e|w|wtf)\(",
        "severity":    "low",
        "category":    "Logging",
        "cwe":         "CWE-532",
        "masvs":       "MASVS-STORAGE-2",
        "owasp":       "M9",
        "description": "App uses Android logging APIs. Log output is accessible to any app with READ_LOGS permission (pre-4.1) or via ADB. Sensitive data (tokens, credentials, PII) in logs is a common finding.",
        "recommendation": "Remove all Log statements from production builds or wrap in BuildConfig.DEBUG checks. Never log sensitive data.",
    },
    {
        "id":          "android_print_stack_trace",
        "title":       "Exception Stack Trace Printed",
        "pattern":     r"printStackTrace\(\)|System\.out\.print|System\.err\.print",
        "severity":    "low",
        "category":    "Logging",
        "cwe":         "CWE-532",
        "masvs":       "MASVS-CODE-4",
        "owasp":       "M9",
        "description": "App prints stack traces or writes to stdout/stderr. This leaks internal class names, file paths, and logic details useful to an attacker.",
        "recommendation": "Use a logging framework (Timber, SLF4J) with production-safe levels. Disable verbose logging in release builds.",
    },

    # ── Network / SSL ─────────────────────────────────────────────────────────
    {
        "id":          "android_trust_all_certs",
        "title":       "TrustManager Accepts All Certificates",
        "pattern":     r"X509TrustManager|TrustAllCerts|checkServerTrusted\(\)|checkClientTrusted\(\)|getAcceptedIssuers\(\)",
        "severity":    "critical",
        "category":    "Network Security",
        "cwe":         "CWE-295",
        "masvs":       "MASVS-NETWORK-2",
        "owasp":       "M5",
        "description": "A custom X509TrustManager implementation detected. If checkServerTrusted() is empty or doesn't throw, it accepts all certificates including self-signed and MitM certificates.",
        "impact":      "Complete SSL/TLS bypass. All HTTPS traffic can be intercepted.",
        "recommendation": "Remove custom TrustManager. Use the default TrustManager and implement certificate pinning via OkHttp or Network Security Config.",
    },
    {
        "id":          "android_allow_all_hostname",
        "title":       "AllowAllHostnameVerifier — Hostname Verification Disabled",
        "pattern":     r"AllowAllHostnameVerifier|ALLOW_ALL_HOSTNAME_VERIFIER|setHostnameVerifier.*ALLOW_ALL|NullHostnameVerifier",
        "severity":    "critical",
        "category":    "Network Security",
        "cwe":         "CWE-297",
        "masvs":       "MASVS-NETWORK-2",
        "owasp":       "M5",
        "description": "Hostname verification is disabled. SSL certificates from any hostname will be accepted, enabling MitM attacks.",
        "recommendation": "Remove AllowAllHostnameVerifier. Use the default HostnameVerifier or implement proper hostname validation.",
    },
    {
        "id":          "android_ssl_no_verify",
        "title":       "SSL Context Configured Without Certificate Validation",
        "pattern":     r"SSLContext\.getInstance\(\"SSL\"\)|setSSLSocketFactory|TrustAll|NoopTrustManager",
        "severity":    "high",
        "category":    "Network Security",
        "cwe":         "CWE-295",
        "masvs":       "MASVS-NETWORK-2",
        "owasp":       "M5",
        "description": "SSLContext may be configured in a way that bypasses certificate validation.",
        "recommendation": "Use the default SSLContext or configure proper TLS certificate validation.",
    },
    {
        "id":          "android_http_connection",
        "title":       "Plaintext HTTP Connection",
        "pattern":     r"http://[a-zA-Z0-9]",
        "severity":    "medium",
        "category":    "Network Security",
        "cwe":         "CWE-319",
        "masvs":       "MASVS-NETWORK-1",
        "owasp":       "M5",
        "description": "Hardcoded HTTP (non-HTTPS) URL detected. Plaintext HTTP is vulnerable to MitM attacks.",
        "recommendation": "Use HTTPS for all network communication.",
    },
    {
        "id":          "android_socket_raw",
        "title":       "Raw Socket Connection",
        "pattern":     r"new Socket\(|ServerSocket\(|DatagramSocket\(",
        "severity":    "low",
        "category":    "Network Security",
        "cwe":         "CWE-319",
        "masvs":       "MASVS-NETWORK-1",
        "owasp":       "M5",
        "description": "Raw socket connections detected. These bypass HTTPS and may transmit data in plaintext.",
        "recommendation": "Use SSLSocket for encrypted raw socket connections. Prefer high-level HTTPS APIs.",
    },

    # ── Runtime / Dynamic Code ────────────────────────────────────────────────
    {
        "id":          "android_runtime_exec",
        "title":       "Runtime.exec() / ProcessBuilder — OS Command Execution",
        # Consolidated (Phase 1.98): union of the former duplicate rule — adds
        # ProcessBuilder so shell execution via either API is covered by ONE rule.
        "pattern":     r"Runtime\.exec\(|Runtime\.getRuntime\(\)\.exec\s*\(|new\s+ProcessBuilder\s*\(",
        "severity":    "high",
        "category":    "Code Execution",
        "cwe":         "CWE-78",
        "masvs":       "MASVS-CODE-4",
        "owasp":       "M4",
        "description": "App executes OS commands via Runtime.exec() or ProcessBuilder. If user-controlled input reaches the command, OS command injection is possible.",
        "recommendation": "Avoid shell execution. If required, pass fixed argv arrays (never a single shell string) and never concatenate user input.",
    },
    {
        "id":          "android_dex_class_loader",
        "title":       "Dynamic Code Loading — DexClassLoader",
        "pattern":     r"DexClassLoader|PathClassLoader|BaseDexClassLoader|InMemoryDexClassLoader",
        "severity":    "high",
        "category":    "Code Quality",
        "cwe":         "CWE-829",
        "masvs":       "MASVS-RESILIENCE-2",
        "owasp":       "M7",
        "description": "App loads DEX/code dynamically at runtime. This can be used for malicious payload delivery or to bypass static analysis.",
        "recommendation": "Avoid dynamic code loading. If required, validate the integrity of loaded code with cryptographic signatures before execution.",
    },
    {
        "id":          "android_reflection",
        "title":       "Java Reflection Usage",
        "pattern":     r"java\.lang\.reflect\.|\.getMethod\(|\.invoke\(|\.getDeclaredMethod\(|\.getDeclaredField\(",
        "severity":    "low",
        "category":    "Code Quality",
        "cwe":         "CWE-470",
        "masvs":       "MASVS-RESILIENCE-3",
        "owasp":       "M7",
        "description": "Java reflection is used. Reflection can be used to bypass access controls, invoke hidden APIs, and is often used in exploits and obfuscation.",
        "recommendation": "Minimize reflection usage. Document legitimate uses. Avoid using reflection to invoke untrusted code.",
    },
    {
        "id":          "android_process_death",
        "title":       "Object Deserialization",
        "pattern":     r"ObjectInputStream|readObject\(\)|Serializable|Parcelable.*readFromParcel",
        "severity":    "medium",
        "category":    "Code Quality",
        "cwe":         "CWE-502",
        "masvs":       "MASVS-CODE-4",
        "owasp":       "M4",
        "description": "App uses Java object deserialization. Unsafe deserialization of attacker-controlled data can lead to remote code execution.",
        "recommendation": "Validate serialized data before deserialization. Use JSON/Protobuf instead of Java serialization where possible.",
    },

    # ── Platform Interaction ──────────────────────────────────────────────────
    {
        "id":          "android_pending_intent_implicit",
        "title":       "Implicit PendingIntent — Intent Hijacking Risk",
        "pattern":     r"PendingIntent\.getActivity\(|PendingIntent\.getService\(|PendingIntent\.getBroadcast\(",
        "severity":    "medium",
        "category":    "Platform Interaction",
        "cwe":         "CWE-927",
        "masvs":       "MASVS-PLATFORM-1",
        "owasp":       "M1",
        "description": "PendingIntent usage detected. If the wrapped Intent is implicit (no explicit component), a malicious app could intercept or redirect it.",
        "recommendation": "Always use explicit Intents within PendingIntents (set component name). Use PendingIntent.FLAG_IMMUTABLE on Android 12+.",
    },
    {
        "id":          "android_sticky_broadcast",
        "title":       "Sticky Broadcast Used",
        "pattern":     r"sendStickyBroadcast\(|sendStickyOrderedBroadcast\(",
        "severity":    "medium",
        "category":    "Platform Interaction",
        "cwe":         "CWE-927",
        "masvs":       "MASVS-PLATFORM-1",
        "owasp":       "M1",
        "description": "Sticky broadcasts are deprecated (API 21+) and present a security risk. Any app can read the sticky broadcast data.",
        "recommendation": "Replace sticky broadcasts with LocalBroadcastManager or other IPC mechanisms.",
    },
    {
        "id":          "android_clipboard_access",
        "title":       "Clipboard Monitoring / Access",
        "pattern":     r"ClipboardManager|getSystemService.*CLIPBOARD|setPrimaryClip\(|getPrimaryClip\(",
        "severity":    "low",
        "category":    "Platform Interaction",
        "cwe":         "CWE-200",
        "masvs":       "MASVS-PLATFORM-1",
        "owasp":       "M6",
        "description": "App accesses the system clipboard. Sensitive data (passwords, credit cards, tokens) may be read from or written to the clipboard.",
        "recommendation": "Clear clipboard contents after use. Avoid copying sensitive data to the clipboard.",
    },
    {
        "id":          "android_intent_scheme_filter",
        "title":       "Intent Scheme URL Processing",
        "pattern":     r"intent://|Intent\.parseUri\(|Intent\.getIntent\(",
        "severity":    "high",
        "category":    "Platform Interaction",
        "cwe":         "CWE-926",
        "masvs":       "MASVS-PLATFORM-1",
        "owasp":       "M1",
        "description": "App processes intent:// scheme URLs. This can be abused to invoke internal intents from web content, potentially bypassing exported=false protections.",
        "recommendation": "Sanitize intent:// URIs before processing. Disallow intent scheme in WebViews unless absolutely required.",
    },

    # ── Resilience / Anti-Tamper ───────────────────────────────────────────────
    {
        "id":          "android_no_root_detection",
        "title":       "No Root Detection Implemented",
        "pattern":     r"su\b|RootBeer|SafetyNet|isRooted|isDeviceRooted|checkRootMethod",
        "severity":    "info",
        "category":    "Resilience",
        "cwe":         "CWE-693",
        "masvs":       "MASVS-RESILIENCE-1",
        "owasp":       "M8",
        "description": "Root detection APIs detected in app. Rooted devices allow bypassing many Android security controls.",
        "recommendation": "Implement multi-layered root detection (RootBeer + SafetyNet/Play Integrity API). Consider blocking functionality on rooted devices for sensitive apps.",
    },
    {
        "id":          "android_no_screenshot_prevention",
        "title":       "Screenshot Prevention Not Detected",
        "pattern":     r"FLAG_SECURE|WindowManager\.LayoutParams\.FLAG_SECURE",
        "severity":    "info",
        "category":    "Resilience",
        "cwe":         "CWE-200",
        "masvs":       "MASVS-STORAGE-1",
        "owasp":       "M9",
        "description": "FLAG_SECURE may not be set. Without it, sensitive screens can be captured in screenshots and app switcher thumbnails.",
        "recommendation": "Set WindowManager.LayoutParams.FLAG_SECURE on activities displaying sensitive data.",
    },
    {
        "id":          "android_frida_detection",
        "title":       "Frida / Dynamic Analysis Detection",
        "pattern":     r"frida|fridaGadget|com\.frida|anti.frida|gadget",
        "severity":    "info",
        "category":    "Resilience",
        "cwe":         "CWE-693",
        "masvs":       "MASVS-RESILIENCE-4",
        "owasp":       "M7",
        "description": "Frida detection logic detected. App attempts to detect dynamic analysis tooling.",
        "recommendation": "N/A — Informational. Note that Frida detection can typically be bypassed.",
    },
    {
        "id":          "android_emulator_detection",
        "title":       "Emulator Detection",
        "pattern":     r"isEmulator|Build\.FINGERPRINT.*generic|Build\.MODEL.*Emulator|android\.os\.Build\.PRODUCT.*sdk",
        "severity":    "info",
        "category":    "Resilience",
        "cwe":         "CWE-693",
        "masvs":       "MASVS-RESILIENCE-1",
        "owasp":       "M7",
        "description": "Emulator detection code detected in app.",
        "recommendation": "N/A — Informational. Emulator detection is easily bypassed via property spoofing.",
    },

    # ── Insecure Intent / IPC ──────────────────────────────────────────────────
    {
        "id":          "android_implicit_intent_sensitive",
        "title":       "Implicit Intent for Sensitive Operation",
        "pattern":     r"new Intent\(\)|Intent\(\).*setAction\(",
        "severity":    "low",
        "category":    "Platform Interaction",
        "cwe":         "CWE-927",
        "masvs":       "MASVS-PLATFORM-1",
        "owasp":       "M1",
        "description": "Implicit intents detected. These can be intercepted by malicious apps that register for the same action.",
        "recommendation": "Use explicit intents (specifying the target component) for sensitive IPC. Use LocalBroadcastManager for local broadcasts.",
    },
    {
        "id":          "android_content_provider_no_permission",
        "title":       "ContentProvider Query Without Permission Check",
        "pattern":     r"getContentResolver\(\)\.query\(|contentResolver\.query\(",
        "severity":    "low",
        "category":    "Platform Interaction",
        "cwe":         "CWE-284",
        "masvs":       "MASVS-PLATFORM-1",
        "owasp":       "M1",
        "description": "ContentProvider queries detected. Ensure the target provider is protected with appropriate permissions.",
        "recommendation": "Verify target ContentProvider has proper read/write permissions. Sanitize URI inputs to prevent path traversal.",
    },

    # ── Data Transmission ──────────────────────────────────────────────────────
    {
        "id":          "android_send_sms_code",
        "title":       "SMS Sending via Code",
        "pattern":     r"SmsManager\.getDefault\(\)|sendTextMessage\(|sendMultipartTextMessage\(",
        "severity":    "medium",
        "category":    "Platform Interaction",
        "cwe":         "CWE-862",
        "masvs":       "MASVS-PLATFORM-1",
        "owasp":       "M6",
        "description": "App programmatically sends SMS messages. Malicious use could result in premium SMS charges or data exfiltration.",
        "recommendation": "Ensure SMS sending is user-initiated and requires explicit confirmation. Log and limit frequency.",
    },
    {
        "id":          "android_phone_call_code",
        "title":       "Phone Call Initiated via Code",
        "pattern":     r"ACTION_CALL|tel:|android\.intent\.action\.CALL",
        "severity":    "medium",
        "category":    "Platform Interaction",
        "cwe":         "CWE-862",
        "masvs":       "MASVS-PLATFORM-1",
        "owasp":       "M6",
        "description": "App can initiate phone calls programmatically. This requires CALL_PHONE permission.",
        "recommendation": "Prefer ACTION_DIAL (user-confirmed) over ACTION_CALL (immediate). Require explicit user interaction.",
    },

    # ── Firebase Specific ─────────────────────────────────────────────────────
    {
        "id":          "android_firebase_no_auth",
        "title":       "Firebase Realtime Database — Unauthenticated Access Risk",
        "pattern":     r"firebaseio\.com|FirebaseDatabase\.getInstance\(\)\.getReference\(",
        "severity":    "medium",
        "category":    "Cloud Configuration",
        "cwe":         "CWE-284",
        "masvs":       "MASVS-NETWORK-1",
        "owasp":       "M8",
        "description": "Firebase Realtime Database usage detected. If security rules are not configured, the database may allow unauthenticated read/write access.",
        "recommendation": "Configure Firebase security rules to require authentication. Test rules at firebase.google.com/docs/rules. Check URL in browser: append .json to get raw data.",
        "poc":         "# Test unauthenticated access:\ncurl https://<project>.firebaseio.com/.json\ncurl https://<project>.firebaseio.com/users.json",
    },
    {
        "id":          "android_google_cloud_storage",
        "title":       "Google Cloud Storage Bucket Reference",
        "pattern":     r"storage\.googleapis\.com|gs://[a-z0-9\-]+",
        "severity":    "medium",
        "category":    "Cloud Configuration",
        "cwe":         "CWE-284",
        "masvs":       "MASVS-NETWORK-1",
        "owasp":       "M8",
        "description": "Google Cloud Storage bucket URL detected. Check if bucket is publicly accessible.",
        "recommendation": "Ensure GCS bucket IAM policies require authentication. Use signed URLs for time-limited access.",
    },

    # ── Debug / Test Code ──────────────────────────────────────────────────────
    {
        "id":          "android_debuggable_check",
        "title":       "Debuggable Flag Check in Code",
        "pattern":     r"BuildConfig\.DEBUG|ApplicationInfo\.FLAG_DEBUGGABLE|isDebuggable",
        "severity":    "info",
        "category":    "Configuration",
        "cwe":         "CWE-489",
        "masvs":       "MASVS-CODE-4",
        "owasp":       "M7",
        "description": "App checks debug flag at runtime. Ensure debug code is properly excluded from release builds.",
        "recommendation": "Verify that debug-only code paths are properly guarded and excluded from release builds.",
    },
    {
        "id":          "android_hardcoded_ip",
        "title":       "Hardcoded IP Address",
        "pattern":     r"\b(?:10\.|192\.168\.|172\.(?:1[6-9]|2\d|3[01])\.|127\.0\.0\.1)\d{0,3}\b|\b\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}\b",
        "severity":    "low",
        "category":    "Configuration",
        "cwe":         "CWE-547",
        "masvs":       "MASVS-CODE-4",
        "owasp":       "M8",
        "description": "Hardcoded IP address detected. Private IPs suggest test/dev server references. Public IPs may expose infrastructure.",
        "recommendation": "Use domain names instead of hardcoded IPs. Remove all development server references from production builds.",
    },
    {
        "id":          "android_obfuscation_missing",
        "title":       "Code Obfuscation Not Detected",
        "pattern":     r"BuildConfig|R\.layout\.|R\.id\.|R\.string\.",
        "severity":    "info",
        "category":    "Resilience",
        "cwe":         "CWE-656",
        "masvs":       "MASVS-RESILIENCE-3",
        "owasp":       "M7",
        "description": "Readable class/resource names suggest code obfuscation may not be applied. Without ProGuard/R8, the full app logic is readable after decompilation.",
        "recommendation": "Enable ProGuard/R8 minification in release builds. Apply obfuscation rules for sensitive code paths.",
    },
]

# ─── iOS / Swift SAST Rules ───────────────────────────────────────────────────
IOS_CODE_RULES = [
    {
        "id":          "ios_ats_disabled",
        "title":       "App Transport Security Disabled",
        "pattern":     r"NSAllowsArbitraryLoads.*true|NSExceptionAllowsInsecureHTTPLoads.*true",
        "severity":    "high",
        "category":    "Network Security",
        "cwe":         "CWE-319",
        "masvs":       "MASVS-NETWORK-1",
        "owasp":       "M5",
        "description": "ATS is disabled, allowing cleartext HTTP connections.",
        "recommendation": "Remove NSAllowsArbitraryLoads. Use HTTPS for all connections.",
    },
    {
        "id":          "ios_md5_hash",
        "title":       "MD5 Hash Function Used",
        "pattern":     r"CC_MD5|CommonCrypto.*MD5|\.md5\b",
        "severity":    "high",
        "category":    "Cryptography",
        "cwe":         "CWE-327",
        "masvs":       "MASVS-CRYPTO-1",
        "owasp":       "M10",
        "description": "MD5 is a broken cryptographic hash function.",
        "recommendation": "Use SHA-256 via CryptoKit (iOS 13+) or CommonCrypto CC_SHA256.",
    },
    {
        "id":          "ios_sha1_hash",
        "title":       "SHA-1 Hash Function Used",
        "pattern":     r"CC_SHA1|\.sha1\b",
        "severity":    "medium",
        "category":    "Cryptography",
        "cwe":         "CWE-327",
        "masvs":       "MASVS-CRYPTO-1",
        "owasp":       "M10",
        "description": "SHA-1 is deprecated for security use.",
        "recommendation": "Migrate to SHA-256 or SHA-3.",
    },
    {
        "id":          "ios_insecure_random",
        "title":       "Insecure Random — arc4random",
        "pattern":     r"\barc4random\b|\brand\(\b",
        "severity":    "medium",
        "category":    "Cryptography",
        "cwe":         "CWE-338",
        "masvs":       "MASVS-CRYPTO-1",
        "owasp":       "M10",
        "description": "arc4random / rand() used. Not suitable for security-sensitive operations.",
        "recommendation": "Use SecRandomCopyBytes() for cryptographically secure random numbers.",
    },
    {
        "id":          "ios_keychain_without_protection",
        "title":       "Keychain Item Without Access Control",
        "pattern":     r"kSecAttrAccessible.*Always|kSecAttrAccessibleAlways\b",
        "severity":    "high",
        "category":    "Data Storage",
        "cwe":         "CWE-312",
        "masvs":       "MASVS-STORAGE-1",
        "owasp":       "M9",
        "description": "Keychain item stored with kSecAttrAccessibleAlways or kSecAttrAccessibleAlwaysThisDeviceOnly. This item is accessible even when the device is locked.",
        "recommendation": "Use kSecAttrAccessibleWhenUnlocked or kSecAttrAccessibleWhenPasscodeSetThisDeviceOnly for sensitive credentials.",
    },
    {
        "id":          "ios_nsuserdefaults_sensitive",
        "title":       "NSUserDefaults for Sensitive Data",
        "pattern":     r"NSUserDefaults\.standard|UserDefaults\.standard",
        "severity":    "medium",
        "category":    "Data Storage",
        "cwe":         "CWE-312",
        "masvs":       "MASVS-STORAGE-1",
        "owasp":       "M9",
        "description": "NSUserDefaults detected. This data is stored in plaintext plist files and included in unencrypted backups. Not suitable for sensitive data.",
        "recommendation": "Use Keychain for sensitive data (credentials, tokens). Do not store PII or secrets in NSUserDefaults.",
    },
    {
        "id":          "ios_nslog_sensitive",
        "title":       "NSLog — Debug Logging in Code",
        "pattern":     r"\bNSLog\(|\bprint\(|\bprintln\(",
        "severity":    "low",
        "category":    "Logging",
        "cwe":         "CWE-532",
        "masvs":       "MASVS-STORAGE-2",
        "owasp":       "M9",
        "description": "NSLog/print statements detected. May log sensitive data accessible via device console.",
        "recommendation": "Remove all NSLog statements from production builds or wrap in #if DEBUG conditionals.",
    },
    {
        "id":          "ios_webview_allow_file",
        "title":       "WKWebView File Access Allowed",
        "pattern":     r"allowFileAccessFromFileURLs|allowUniversalAccessFromFileURLs",
        "severity":    "high",
        "category":    "WebView",
        "cwe":         "CWE-200",
        "masvs":       "MASVS-PLATFORM-2",
        "owasp":       "M1",
        "description": "WKWebView is configured to allow file access from file URLs. JavaScript in the WebView can read arbitrary local files.",
        "recommendation": "Do not set allowFileAccessFromFileURLs or allowUniversalAccessFromFileURLs to true.",
    },
    {
        "id":          "ios_uipasteboard_sensitive",
        "title":       "UIPasteboard / Clipboard Access",
        "pattern":     r"UIPasteboard\.general|UIPasteboard\.withUniqueName",
        "severity":    "low",
        "category":    "Platform Interaction",
        "cwe":         "CWE-200",
        "masvs":       "MASVS-PLATFORM-1",
        "owasp":       "M6",
        "description": "App accesses the system clipboard. Sensitive data may be exposed.",
        "recommendation": "Clear clipboard after use. Do not copy sensitive data to clipboard.",
    },
    {
        "id":          "ios_sqlite_raw_query",
        "title":       "SQLite Raw Query — SQL Injection Risk",
        "pattern":     r"sqlite3_exec\(|sqlite3_prepare_v2\(",
        "severity":    "high",
        "category":    "Data Storage",
        "cwe":         "CWE-89",
        "masvs":       "MASVS-CODE-4",
        "owasp":       "M4",
        "description": "Raw SQLite queries detected. If user-controlled input is concatenated into SQL strings, SQL injection is possible.",
        "recommendation": "Use parameterized queries (? placeholders with sqlite3_bind_*). Consider Core Data or FMDB.",
    },
    {
        "id":          "ios_realm_no_encryption",
        "title":       "Realm Database Without Encryption",
        "pattern":     r"Realm\.Configuration\(\)|try! Realm\(\)|Realm()",
        "severity":    "medium",
        "category":    "Data Storage",
        "cwe":         "CWE-312",
        "masvs":       "MASVS-STORAGE-1",
        "owasp":       "M9",
        "description": "Realm database usage detected without explicit encryption configuration.",
        "recommendation": "Use Realm encryption with a key stored in the Keychain.",
    },
    {
        "id":          "ios_hardcoded_credentials",
        "title":       "Hardcoded Credentials in Swift/ObjC",
        "pattern":     r'(?:password|secret|token|api.?key)\s*=\s*"[^"]{6,}"',
        "severity":    "high",
        "category":    "Credentials",
        "cwe":         "CWE-798",
        "masvs":       "MASVS-CRYPTO-2",
        "owasp":       "M1",
        "description": "Hardcoded credential string detected in Swift or Objective-C code.",
        "recommendation": "Store credentials in Keychain. Load from secure server-side configuration at runtime.",
    },
    {
        "id":          "ios_jailbreak_detection",
        "title":       "Jailbreak Detection Logic",
        "pattern":     r"cydia|substrate|MobileSubstrate|jailbreak|\.installed.*Cydia|fileExists.*Applications|/bin/bash",
        "severity":    "info",
        "category":    "Resilience",
        "cwe":         "CWE-693",
        "masvs":       "MASVS-RESILIENCE-1",
        "owasp":       "M7",
        "description": "Jailbreak detection code detected. App checks for signs of a jailbroken device.",
        "recommendation": "N/A — Informational. Jailbreak detection can typically be bypassed with tools like Liberty Lite or Choicy.",
    },

    # ── Additional Android rules ──────────────────────────────────────────────
    {
        "id":          "android_webview_file_access_from_file_urls",
        "title":       "WebView Allows File Access From File URLs",
        "pattern":     r"setAllowFileAccessFromFileURLs\s*\(\s*true\s*\)|setAllowUniversalAccessFromFileURLs\s*\(\s*true\s*\)",
        "severity":    "high",
        "category":    "WebView",
        "cwe":         "CWE-200",
        "masvs":       "MASVS-PLATFORM-2",
        "owasp":       "M4",
        "description": "WebView permits file:// URLs to read other local files or issue cross-origin requests. Enables local file disclosure through XSS in loaded HTML.",
        "recommendation": "Leave both settings at their default (false). If loading local HTML, sanitize aggressively and consider WebViewAssetLoader.",
    },
    {
        "id":          "android_intent_redirect",
        "title":       "Potential Intent Redirection",
        "pattern":     r"getIntent\(\)\.(?:getParcelableExtra|getSerializableExtra)\([^)]*\)\s*;?\s*(?:[^;]*startActivity|startActivityForResult)",
        "severity":    "high",
        "category":    "IPC",
        "cwe":         "CWE-926",
        "masvs":       "MASVS-PLATFORM-1",
        "owasp":       "M4",
        "description": "App extracts an Intent from an incoming Intent and starts it without validation — an attacker-controlled Intent can launch arbitrary protected activities.",
        "recommendation": "Validate the forwarded Intent's component, action, and data. Reject Intents that don't match an allowlist.",
    },
    {
        "id":          "android_insecure_broadcast_register",
        "title":       "BroadcastReceiver Registered Without RECEIVER_EXPORTED Flag",
        "pattern":     r"registerReceiver\s*\([^,]+,[^,)]+\)(?!\s*,)",
        "severity":    "medium",
        "category":    "IPC",
        "cwe":         "CWE-926",
        "masvs":       "MASVS-PLATFORM-1",
        "owasp":       "M4",
        "description": "Dynamic receiver registered without the Android 14+ export flag. On older APIs this defaults to exported, accepting broadcasts from any app.",
        "recommendation": "Pass RECEIVER_NOT_EXPORTED (or RECEIVER_EXPORTED with a permission) when calling registerReceiver.",
    },
    {
        "id":          "android_insecure_content_resolver_query",
        "title":       "ContentResolver Query Built With String Concatenation",
        "pattern":     r"getContentResolver\(\)\.query\([^)]*\+[^)]*\)",
        "severity":    "high",
        "category":    "SQLi",
        "cwe":         "CWE-89",
        "masvs":       "MASVS-CODE-1",
        "owasp":       "M4",
        "description": "ContentResolver.query selection string is built with + concatenation — possibly includes user input leading to SQL injection in the backing provider.",
        "recommendation": "Use the selectionArgs parameter (parameterized '?') instead of string concatenation.",
    },
    {
        "id":          "android_pending_intent_mutable",
        "title":       "Mutable PendingIntent Created",
        "pattern":     r"PendingIntent\.(?:getActivity|getBroadcast|getService)\s*\([^)]*FLAG_MUTABLE",
        "severity":    "medium",
        "category":    "IPC",
        "cwe":         "CWE-927",
        "masvs":       "MASVS-PLATFORM-1",
        "owasp":       "M4",
        "description": "Mutable PendingIntent lets third parties fill empty Intent fields. If the base Intent is implicit, the receiver can redirect the callback to arbitrary components.",
        "recommendation": "Use FLAG_IMMUTABLE unless you specifically need fillIn(). If mutable is required, make the base Intent explicit.",
    },
    {
        "id":          "android_fileprovider_any_path",
        "title":       "FileProvider Exposes Wide File Paths",
        "pattern":     r"<root-path\s|<external-path\s+name=\"[^\"]*\"\s+path=\"[./]*\"|<files-path\s+name=\"[^\"]*\"\s+path=\"[./]*\"",
        "severity":    "high",
        "category":    "Data Leak",
        "cwe":         "CWE-552",
        "masvs":       "MASVS-STORAGE-1",
        "owasp":       "M9",
        "description": "FileProvider paths.xml shares the entire external storage or root — any file on device may be read by apps granted a URI permission.",
        "recommendation": "Declare narrow sub-paths (e.g. images/). Never expose root-path or empty path values.",
    },
    {
        "id":          "android_frida_gadget",
        "title":       "Frida Gadget Artifact Found",
        "pattern":     r"frida-gadget|re\.frida\.server|libfrida-gadget\.so|gum-js-loop|linjector",
        "severity":    "critical",
        "category":    "Tampering",
        "cwe":         "CWE-506",
        "masvs":       "MASVS-RESILIENCE-2",
        "owasp":       "M7",
        "description": "Artifacts of the Frida dynamic instrumentation gadget detected. If present in production APK, the app is instrumented and not safe to ship.",
        "recommendation": "Remove Frida gadget from release builds. Add runtime detection for Frida, objection, and Xposed.",
    },
    {
        "id":          "android_smali_insecure_hostname_verifier",
        "title":       "AllowAllHostnameVerifier / NullHostnameVerifier",
        "pattern":     r"AllowAllHostnameVerifier|NullHostnameVerifier|ALLOW_ALL_HOSTNAME_VERIFIER",
        "severity":    "critical",
        "category":    "Network",
        "cwe":         "CWE-297",
        "masvs":       "MASVS-NETWORK-1",
        "owasp":       "M5",
        "description": "App uses a hostname verifier that accepts any hostname — fully defeats TLS host identity checks.",
        "recommendation": "Use the default HostnameVerifier. For pinning, use OkHttp CertificatePinner or Network Security Config pin-set.",
    },
    {
        "id":          "android_clear_text_traffic_permitted",
        "title":       "Network Security Config Permits Cleartext",
        "pattern":     r"cleartextTrafficPermitted=\"true\"|android:usesCleartextTraffic=\"true\"",
        "severity":    "high",
        "category":    "Network",
        "cwe":         "CWE-319",
        "masvs":       "MASVS-NETWORK-1",
        "owasp":       "M5",
        "description": "Network Security Config or manifest allows cleartext (http://) traffic — data is unencrypted on the wire.",
        "recommendation": "Set cleartextTrafficPermitted=false. Use https:// everywhere or domain-specific exceptions.",
    },
    {
        "id":          "android_debuggable_backup_true",
        "title":       "android:allowBackup Enabled",
        "pattern":     r"android:allowBackup=\"true\"",
        "severity":    "medium",
        "category":    "Misconfiguration",
        "cwe":         "CWE-530",
        "masvs":       "MASVS-STORAGE-1",
        "owasp":       "M8",
        "description": "Manifest permits adb backup of app data — an attacker with USB debugging access can dump the entire sandbox.",
        "recommendation": "Set android:allowBackup=\"false\" or provide a tight android:fullBackupContent rule.",
    },
    {
        "id":          "android_trust_manager_accept_all",
        "title":       "Custom X509TrustManager Accepts All Certificates",
        "pattern":     r"checkServerTrusted\s*\([^)]*\)\s*(?:throws\s+[^{]+)?\{\s*\}",
        "severity":    "critical",
        "category":    "Network",
        "cwe":         "CWE-295",
        "masvs":       "MASVS-NETWORK-1",
        "owasp":       "M5",
        "description": "checkServerTrusted is overridden with an empty body — all TLS certificates, including attacker-forged ones, are accepted.",
        "recommendation": "Delegate to the system TrustManager. Use certificate pinning via OkHttp or NSC pin-set rather than custom trust managers.",
    },
    {
        "id":          "android_root_detection_bypass_strings",
        "title":       "Magisk / Root Cloak Strings Present",
        "pattern":     r"com\.topjohnwu\.magisk|MagiskHide|io\.github\.vvb2060\.mahoshojo|com\.kingroot\.kinguser|com\.noshufou\.android\.su",
        "severity":    "info",
        "category":    "Resilience",
        "cwe":         "CWE-693",
        "masvs":       "MASVS-RESILIENCE-1",
        "owasp":       "M7",
        "description": "Strings referencing common root / root-cloak packages detected. May indicate root-detection logic or a reference list for bypass.",
        "recommendation": "Ensure root detection checks are layered (file checks, mount checks, native syscall checks) to resist Magisk DenyList.",
    },
    {
        "id":          "android_sharedprefs_world_readable",
        "title":       "SharedPreferences Opened MODE_WORLD_READABLE / WORLD_WRITEABLE",
        "pattern":     r"MODE_WORLD_READABLE|MODE_WORLD_WRITEABLE|getSharedPreferences\([^,]+,\s*(?:1|2)\s*\)",
        "severity":    "high",
        "category":    "Data Storage",
        "cwe":         "CWE-276",
        "masvs":       "MASVS-STORAGE-1",
        "owasp":       "M9",
        "description": "Legacy world-readable/writable mode exposes SharedPreferences to any app on pre-Android 7 devices.",
        "recommendation": "Always use MODE_PRIVATE. For sensitive data, use EncryptedSharedPreferences (Jetpack Security).",
    },
]
